/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Componentes_Graficos;

import java.awt.Component;
import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author daw-B
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        vDatos = new ArrayList<>();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones_Introduccion_Muestra = new javax.swing.ButtonGroup();
        jDatos_usuario = new javax.swing.JPanel();
        jTelefono = new javax.swing.JTextField();
        jNombre_Usuario = new javax.swing.JTextField();
        jGuardar_Datos_Usuario = new javax.swing.JButton();
        jEdad = new javax.swing.JSpinner();
        jEdad_Etiqueta = new javax.swing.JLabel();
        jExit = new javax.swing.JButton();
        jActivar_Guardado = new javax.swing.JButton();
        jBoton_Introducir_Datos = new javax.swing.JRadioButton();
        jBoton_Mostrar_Datos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMostrar_Datos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jDatos_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Usuario\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jTelefono.setText("Telefono");
        jTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTelefonoMouseClicked(evt);
            }
        });
        jTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefonoActionPerformed(evt);
            }
        });

        jNombre_Usuario.setText("Nombre Usuario");
        jNombre_Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNombre_UsuarioFocusGained(evt);
            }
        });
        jNombre_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNombre_UsuarioMouseClicked(evt);
            }
        });
        jNombre_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombre_UsuarioActionPerformed(evt);
            }
        });

        jGuardar_Datos_Usuario.setText("Guardar");
        jGuardar_Datos_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGuardar_Datos_UsuarioMouseClicked(evt);
            }
        });

        jEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEdadMouseClicked(evt);
            }
        });

        jEdad_Etiqueta.setText("Edad");

        javax.swing.GroupLayout jDatos_usuarioLayout = new javax.swing.GroupLayout(jDatos_usuario);
        jDatos_usuario.setLayout(jDatos_usuarioLayout);
        jDatos_usuarioLayout.setHorizontalGroup(
            jDatos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDatos_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDatos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTelefono)
                    .addComponent(jNombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDatos_usuarioLayout.createSequentialGroup()
                        .addComponent(jEdad_Etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(jGuardar_Datos_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDatos_usuarioLayout.setVerticalGroup(
            jDatos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDatos_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDatos_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEdad_Etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addComponent(jGuardar_Datos_Usuario)
                .addContainerGap())
        );

        jExit.setText("Exit");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
        });

        jActivar_Guardado.setText("Activar Guardado");
        jActivar_Guardado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jActivar_GuardadoMouseClicked(evt);
            }
        });
        jActivar_Guardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActivar_GuardadoActionPerformed(evt);
            }
        });

        Botones_Introduccion_Muestra.add(jBoton_Introducir_Datos);
        jBoton_Introducir_Datos.setText("Introduccion de datos");
        jBoton_Introducir_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBoton_Introducir_DatosMouseClicked(evt);
            }
        });
        jBoton_Introducir_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_Introducir_DatosActionPerformed(evt);
            }
        });

        Botones_Introduccion_Muestra.add(jBoton_Mostrar_Datos);
        jBoton_Mostrar_Datos.setText("muestra de datos");
        jBoton_Mostrar_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBoton_Mostrar_DatosMouseClicked(evt);
            }
        });

        jMostrar_Datos.setColumns(20);
        jMostrar_Datos.setRows(5);
        jScrollPane1.setViewportView(jMostrar_Datos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBoton_Introducir_Datos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBoton_Mostrar_Datos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDatos_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jActivar_Guardado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDatos_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton_Mostrar_Datos)
                    .addComponent(jBoton_Introducir_Datos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jActivar_Guardado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        
        int opc = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que quieres salir?");
        
        if (opc == JOptionPane.YES_OPTION) {
            exit(0);   
        }
    }//GEN-LAST:event_jExitMouseClicked

    private void jTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefonoActionPerformed

    private void jNombre_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombre_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre_UsuarioActionPerformed

    private void jNombre_UsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNombre_UsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre_UsuarioFocusGained

    private void jNombre_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNombre_UsuarioMouseClicked
        jNombre_Usuario.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jNombre_UsuarioMouseClicked

    private void jTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTelefonoMouseClicked
        jTelefono.setText("");
    }//GEN-LAST:event_jTelefonoMouseClicked

    private void jGuardar_Datos_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGuardar_Datos_UsuarioMouseClicked
        
        String nombre, telefono;
        int edad;

        nombre = jNombre_Usuario.getText();
        telefono = jTelefono.getText();
        edad  = (int) jEdad.getValue();
        
        vDatos.add("Nombre : " + nombre + " Telefono : " + telefono + " Edad : " + edad + "\n");
        
        jNombre_Usuario.setText("Nombre Usuario");
        jTelefono.setText("Telefono");
        
        
        JOptionPane.showMessageDialog(rootPane, "Datos " + nombre + " " + telefono + " guardados correctamente");
        
        Component c[] = jDatos_usuario.getComponents();
        for (Component component : c) {
            jGuardar_Datos_Usuario.setEnabled(false);
        }
        
        jMostrar_Datos.setText(vDatos.toString());
        
    }//GEN-LAST:event_jGuardar_Datos_UsuarioMouseClicked

    private void jActivar_GuardadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jActivar_GuardadoMouseClicked

        if (!jGuardar_Datos_Usuario.isEnabled()) {
            jGuardar_Datos_Usuario.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jActivar_GuardadoMouseClicked

    private void jBoton_Introducir_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_Introducir_DatosActionPerformed
        
    }//GEN-LAST:event_jBoton_Introducir_DatosActionPerformed

    private void jActivar_GuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActivar_GuardadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jActivar_GuardadoActionPerformed

    private void jBoton_Mostrar_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_Mostrar_DatosMouseClicked
        
        jDatos_usuario.setVisible(false);
        jMostrar_Datos.setVisible(true);
        
    }//GEN-LAST:event_jBoton_Mostrar_DatosMouseClicked

    private void jBoton_Introducir_DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBoton_Introducir_DatosMouseClicked
        
        jMostrar_Datos.setVisible(false);
        jDatos_usuario.setVisible(true);
        
        
    }//GEN-LAST:event_jBoton_Introducir_DatosMouseClicked

    private void jEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEdadMouseClicked
       
    }//GEN-LAST:event_jEdadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private ArrayList<String> vDatos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones_Introduccion_Muestra;
    private javax.swing.JButton jActivar_Guardado;
    private javax.swing.JRadioButton jBoton_Introducir_Datos;
    private javax.swing.JRadioButton jBoton_Mostrar_Datos;
    private javax.swing.JPanel jDatos_usuario;
    private javax.swing.JSpinner jEdad;
    private javax.swing.JLabel jEdad_Etiqueta;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jGuardar_Datos_Usuario;
    private javax.swing.JTextArea jMostrar_Datos;
    private javax.swing.JTextField jNombre_Usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTelefono;
    // End of variables declaration//GEN-END:variables
}
